// GENERADO POR scripts/gen-countries.mjs — no editar a mano.
// Indicativos: libphonenumber-js. Nombres: Intl.DisplayNames en espanol.
// Regenerar:  node scripts/gen-countries.mjs

export type Country = { iso: string; code: string; name: string; top?: boolean }

/** Los marcados con `top` van primero: son los mercados principales. */
export const COUNTRIES: Country[] = [
  { iso: 'co', code: '57', name: "Colombia", top: true },
  { iso: 'mx', code: '52', name: "México", top: true },
  { iso: 'pe', code: '51', name: "Perú", top: true },
  { iso: 'ec', code: '593', name: "Ecuador", top: true },
  { iso: 'cl', code: '56', name: "Chile", top: true },
  { iso: 'ar', code: '54', name: "Argentina", top: true },
  { iso: 'us', code: '1', name: "Estados Unidos", top: true },
  { iso: 'es', code: '34', name: "España", top: true },
  { iso: 'af', code: '93', name: "Afganistán" },
  { iso: 'al', code: '355', name: "Albania" },
  { iso: 'de', code: '49', name: "Alemania" },
  { iso: 'ad', code: '376', name: "Andorra" },
  { iso: 'ao', code: '244', name: "Angola" },
  { iso: 'ai', code: '1', name: "Anguila" },
  { iso: 'ag', code: '1', name: "Antigua y Barbuda" },
  { iso: 'sa', code: '966', name: "Arabia Saudí" },
  { iso: 'dz', code: '213', name: "Argelia" },
  { iso: 'am', code: '374', name: "Armenia" },
  { iso: 'aw', code: '297', name: "Aruba" },
  { iso: 'au', code: '61', name: "Australia" },
  { iso: 'at', code: '43', name: "Austria" },
  { iso: 'az', code: '994', name: "Azerbaiyán" },
  { iso: 'bs', code: '1', name: "Bahamas" },
  { iso: 'bd', code: '880', name: "Bangladés" },
  { iso: 'bb', code: '1', name: "Barbados" },
  { iso: 'bh', code: '973', name: "Baréin" },
  { iso: 'be', code: '32', name: "Bélgica" },
  { iso: 'bz', code: '501', name: "Belice" },
  { iso: 'bj', code: '229', name: "Benín" },
  { iso: 'bm', code: '1', name: "Bermudas" },
  { iso: 'by', code: '375', name: "Bielorrusia" },
  { iso: 'bo', code: '591', name: "Bolivia" },
  { iso: 'ba', code: '387', name: "Bosnia y Herzegovina" },
  { iso: 'bw', code: '267', name: "Botsuana" },
  { iso: 'br', code: '55', name: "Brasil" },
  { iso: 'bn', code: '673', name: "Brunéi" },
  { iso: 'bg', code: '359', name: "Bulgaria" },
  { iso: 'bf', code: '226', name: "Burkina Faso" },
  { iso: 'bi', code: '257', name: "Burundi" },
  { iso: 'bt', code: '975', name: "Bután" },
  { iso: 'cv', code: '238', name: "Cabo Verde" },
  { iso: 'kh', code: '855', name: "Camboya" },
  { iso: 'cm', code: '237', name: "Camerún" },
  { iso: 'ca', code: '1', name: "Canadá" },
  { iso: 'bq', code: '599', name: "Caribe neerlandés" },
  { iso: 'qa', code: '974', name: "Catar" },
  { iso: 'td', code: '235', name: "Chad" },
  { iso: 'cz', code: '420', name: "Chequia" },
  { iso: 'cn', code: '86', name: "China" },
  { iso: 'cy', code: '357', name: "Chipre" },
  { iso: 'va', code: '39', name: "Ciudad del Vaticano" },
  { iso: 'km', code: '269', name: "Comoras" },
  { iso: 'cg', code: '242', name: "Congo" },
  { iso: 'kp', code: '850', name: "Corea del Norte" },
  { iso: 'kr', code: '82', name: "Corea del Sur" },
  { iso: 'cr', code: '506', name: "Costa Rica" },
  { iso: 'ci', code: '225', name: "Côte d’Ivoire" },
  { iso: 'hr', code: '385', name: "Croacia" },
  { iso: 'cu', code: '53', name: "Cuba" },
  { iso: 'cw', code: '599', name: "Curazao" },
  { iso: 'dk', code: '45', name: "Dinamarca" },
  { iso: 'dm', code: '1', name: "Dominica" },
  { iso: 'eg', code: '20', name: "Egipto" },
  { iso: 'sv', code: '503', name: "El Salvador" },
  { iso: 'ae', code: '971', name: "Emiratos Árabes Unidos" },
  { iso: 'er', code: '291', name: "Eritrea" },
  { iso: 'sk', code: '421', name: "Eslovaquia" },
  { iso: 'si', code: '386', name: "Eslovenia" },
  { iso: 'ee', code: '372', name: "Estonia" },
  { iso: 'sz', code: '268', name: "Esuatini" },
  { iso: 'et', code: '251', name: "Etiopía" },
  { iso: 'ph', code: '63', name: "Filipinas" },
  { iso: 'fi', code: '358', name: "Finlandia" },
  { iso: 'fj', code: '679', name: "Fiyi" },
  { iso: 'fr', code: '33', name: "Francia" },
  { iso: 'ga', code: '241', name: "Gabón" },
  { iso: 'gm', code: '220', name: "Gambia" },
  { iso: 'ge', code: '995', name: "Georgia" },
  { iso: 'gh', code: '233', name: "Ghana" },
  { iso: 'gi', code: '350', name: "Gibraltar" },
  { iso: 'gd', code: '1', name: "Granada" },
  { iso: 'gr', code: '30', name: "Grecia" },
  { iso: 'gl', code: '299', name: "Groenlandia" },
  { iso: 'gp', code: '590', name: "Guadalupe" },
  { iso: 'gu', code: '1', name: "Guam" },
  { iso: 'gt', code: '502', name: "Guatemala" },
  { iso: 'gf', code: '594', name: "Guayana Francesa" },
  { iso: 'gg', code: '44', name: "Guernesey" },
  { iso: 'gn', code: '224', name: "Guinea" },
  { iso: 'gq', code: '240', name: "Guinea Ecuatorial" },
  { iso: 'gw', code: '245', name: "Guinea-Bisáu" },
  { iso: 'gy', code: '592', name: "Guyana" },
  { iso: 'ht', code: '509', name: "Haití" },
  { iso: 'hn', code: '504', name: "Honduras" },
  { iso: 'hu', code: '36', name: "Hungría" },
  { iso: 'in', code: '91', name: "India" },
  { iso: 'id', code: '62', name: "Indonesia" },
  { iso: 'iq', code: '964', name: "Irak" },
  { iso: 'ir', code: '98', name: "Irán" },
  { iso: 'ie', code: '353', name: "Irlanda" },
  { iso: 'ac', code: '247', name: "Isla de la Ascensión" },
  { iso: 'im', code: '44', name: "Isla de Man" },
  { iso: 'cx', code: '61', name: "Isla de Navidad" },
  { iso: 'nf', code: '672', name: "Isla Norfolk" },
  { iso: 'is', code: '354', name: "Islandia" },
  { iso: 'ax', code: '358', name: "Islas Aland" },
  { iso: 'ky', code: '1', name: "Islas Caimán" },
  { iso: 'cc', code: '61', name: "Islas Cocos" },
  { iso: 'ck', code: '682', name: "Islas Cook" },
  { iso: 'fo', code: '298', name: "Islas Feroe" },
  { iso: 'fk', code: '500', name: "Islas Malvinas" },
  { iso: 'mp', code: '1', name: "Islas Marianas del Norte" },
  { iso: 'mh', code: '692', name: "Islas Marshall" },
  { iso: 'sb', code: '677', name: "Islas Salomón" },
  { iso: 'tc', code: '1', name: "Islas Turcas y Caicos" },
  { iso: 'vg', code: '1', name: "Islas Vírgenes Británicas" },
  { iso: 'vi', code: '1', name: "Islas Vírgenes de EE. UU." },
  { iso: 'il', code: '972', name: "Israel" },
  { iso: 'it', code: '39', name: "Italia" },
  { iso: 'jm', code: '1', name: "Jamaica" },
  { iso: 'jp', code: '81', name: "Japón" },
  { iso: 'je', code: '44', name: "Jersey" },
  { iso: 'jo', code: '962', name: "Jordania" },
  { iso: 'kz', code: '7', name: "Kazajistán" },
  { iso: 'ke', code: '254', name: "Kenia" },
  { iso: 'kg', code: '996', name: "Kirguistán" },
  { iso: 'ki', code: '686', name: "Kiribati" },
  { iso: 'xk', code: '383', name: "Kosovo" },
  { iso: 'kw', code: '965', name: "Kuwait" },
  { iso: 'la', code: '856', name: "Laos" },
  { iso: 'ls', code: '266', name: "Lesoto" },
  { iso: 'lv', code: '371', name: "Letonia" },
  { iso: 'lb', code: '961', name: "Líbano" },
  { iso: 'lr', code: '231', name: "Liberia" },
  { iso: 'ly', code: '218', name: "Libia" },
  { iso: 'li', code: '423', name: "Liechtenstein" },
  { iso: 'lt', code: '370', name: "Lituania" },
  { iso: 'lu', code: '352', name: "Luxemburgo" },
  { iso: 'mk', code: '389', name: "Macedonia del Norte" },
  { iso: 'mg', code: '261', name: "Madagascar" },
  { iso: 'my', code: '60', name: "Malasia" },
  { iso: 'mw', code: '265', name: "Malaui" },
  { iso: 'mv', code: '960', name: "Maldivas" },
  { iso: 'ml', code: '223', name: "Mali" },
  { iso: 'mt', code: '356', name: "Malta" },
  { iso: 'ma', code: '212', name: "Marruecos" },
  { iso: 'mq', code: '596', name: "Martinica" },
  { iso: 'mu', code: '230', name: "Mauricio" },
  { iso: 'mr', code: '222', name: "Mauritania" },
  { iso: 'yt', code: '262', name: "Mayotte" },
  { iso: 'fm', code: '691', name: "Micronesia" },
  { iso: 'md', code: '373', name: "Moldavia" },
  { iso: 'mc', code: '377', name: "Mónaco" },
  { iso: 'mn', code: '976', name: "Mongolia" },
  { iso: 'me', code: '382', name: "Montenegro" },
  { iso: 'ms', code: '1', name: "Montserrat" },
  { iso: 'mz', code: '258', name: "Mozambique" },
  { iso: 'mm', code: '95', name: "Myanmar (Birmania)" },
  { iso: 'na', code: '264', name: "Namibia" },
  { iso: 'nr', code: '674', name: "Nauru" },
  { iso: 'np', code: '977', name: "Nepal" },
  { iso: 'ni', code: '505', name: "Nicaragua" },
  { iso: 'ne', code: '227', name: "Níger" },
  { iso: 'ng', code: '234', name: "Nigeria" },
  { iso: 'nu', code: '683', name: "Niue" },
  { iso: 'no', code: '47', name: "Noruega" },
  { iso: 'nc', code: '687', name: "Nueva Caledonia" },
  { iso: 'nz', code: '64', name: "Nueva Zelanda" },
  { iso: 'om', code: '968', name: "Omán" },
  { iso: 'nl', code: '31', name: "Países Bajos" },
  { iso: 'pk', code: '92', name: "Pakistán" },
  { iso: 'pw', code: '680', name: "Palaos" },
  { iso: 'pa', code: '507', name: "Panamá" },
  { iso: 'pg', code: '675', name: "Papúa Nueva Guinea" },
  { iso: 'py', code: '595', name: "Paraguay" },
  { iso: 'pf', code: '689', name: "Polinesia Francesa" },
  { iso: 'pl', code: '48', name: "Polonia" },
  { iso: 'pt', code: '351', name: "Portugal" },
  { iso: 'pr', code: '1', name: "Puerto Rico" },
  { iso: 'hk', code: '852', name: "RAE de Hong Kong (China)" },
  { iso: 'mo', code: '853', name: "RAE de Macao (China)" },
  { iso: 'gb', code: '44', name: "Reino Unido" },
  { iso: 'cf', code: '236', name: "República Centroafricana" },
  { iso: 'cd', code: '243', name: "República Democrática del Congo" },
  { iso: 'do', code: '1', name: "República Dominicana" },
  { iso: 're', code: '262', name: "Reunión" },
  { iso: 'rw', code: '250', name: "Ruanda" },
  { iso: 'ro', code: '40', name: "Rumanía" },
  { iso: 'ru', code: '7', name: "Rusia" },
  { iso: 'eh', code: '212', name: "Sáhara Occidental" },
  { iso: 'ws', code: '685', name: "Samoa" },
  { iso: 'as', code: '1', name: "Samoa Americana" },
  { iso: 'bl', code: '590', name: "San Bartolomé" },
  { iso: 'kn', code: '1', name: "San Cristóbal y Nieves" },
  { iso: 'sm', code: '378', name: "San Marino" },
  { iso: 'mf', code: '590', name: "San Martín" },
  { iso: 'pm', code: '508', name: "San Pedro y Miquelón" },
  { iso: 'vc', code: '1', name: "San Vicente y las Granadinas" },
  { iso: 'sh', code: '290', name: "Santa Elena" },
  { iso: 'lc', code: '1', name: "Santa Lucía" },
  { iso: 'st', code: '239', name: "Santo Tomé y Príncipe" },
  { iso: 'sn', code: '221', name: "Senegal" },
  { iso: 'rs', code: '381', name: "Serbia" },
  { iso: 'sc', code: '248', name: "Seychelles" },
  { iso: 'sl', code: '232', name: "Sierra Leona" },
  { iso: 'sg', code: '65', name: "Singapur" },
  { iso: 'sx', code: '1', name: "Sint Maarten" },
  { iso: 'sy', code: '963', name: "Siria" },
  { iso: 'so', code: '252', name: "Somalia" },
  { iso: 'lk', code: '94', name: "Sri Lanka" },
  { iso: 'za', code: '27', name: "Sudáfrica" },
  { iso: 'sd', code: '249', name: "Sudán" },
  { iso: 'ss', code: '211', name: "Sudán del Sur" },
  { iso: 'se', code: '46', name: "Suecia" },
  { iso: 'ch', code: '41', name: "Suiza" },
  { iso: 'sr', code: '597', name: "Surinam" },
  { iso: 'sj', code: '47', name: "Svalbard y Jan Mayen" },
  { iso: 'th', code: '66', name: "Tailandia" },
  { iso: 'tw', code: '886', name: "Taiwán" },
  { iso: 'tz', code: '255', name: "Tanzania" },
  { iso: 'tj', code: '992', name: "Tayikistán" },
  { iso: 'io', code: '246', name: "Territorio Británico del Océano Índico" },
  { iso: 'ps', code: '970', name: "Territorios Palestinos" },
  { iso: 'tl', code: '670', name: "Timor-Leste" },
  { iso: 'tg', code: '228', name: "Togo" },
  { iso: 'tk', code: '690', name: "Tokelau" },
  { iso: 'to', code: '676', name: "Tonga" },
  { iso: 'tt', code: '1', name: "Trinidad y Tobago" },
  { iso: 'ta', code: '290', name: "Tristán de Acuña" },
  { iso: 'tn', code: '216', name: "Túnez" },
  { iso: 'tm', code: '993', name: "Turkmenistán" },
  { iso: 'tr', code: '90', name: "Turquía" },
  { iso: 'tv', code: '688', name: "Tuvalu" },
  { iso: 'ua', code: '380', name: "Ucrania" },
  { iso: 'ug', code: '256', name: "Uganda" },
  { iso: 'uy', code: '598', name: "Uruguay" },
  { iso: 'uz', code: '998', name: "Uzbekistán" },
  { iso: 'vu', code: '678', name: "Vanuatu" },
  { iso: 've', code: '58', name: "Venezuela" },
  { iso: 'vn', code: '84', name: "Vietnam" },
  { iso: 'wf', code: '681', name: "Wallis y Futuna" },
  { iso: 'ye', code: '967', name: "Yemen" },
  { iso: 'dj', code: '253', name: "Yibuti" },
  { iso: 'zm', code: '260', name: "Zambia" },
  { iso: 'zw', code: '263', name: "Zimbabue" },
]

export const DEFAULT_ISO = 'co'
export const DEFAULT_DIAL = '57'
